### ISSUE TITLE
_self should be relative to macro files too

### ISSUE THREAD

**Issue by soywiz** [soywiz/atpl.js#69]

**Comment by InDIOS** [comment]
Hi, great job with this template engine. I had some problems with the use of variable **_self** in **macros**, and making debug in the source code I could see a very simple solution, did the tests, specifically the test disabled in the **fixtures_disabled** folder, named **_self_other_file** and everything was fine. I do not put the code here because it goes in different parts of the file and the file is very long. The solution solved the problem when we have to import a macro in the same file, complying with the [Twig macro](http://twig.sensiolabs.org/doc/tags/macro.html) documentation. I had other problem when i use [consolidate](https://github.com/tj/consolidate.js) module and i also solved with an if condition. I did a fork of this wonderful project and put my contribution [there](https://github.com/InDIOS/atpl.js) (the changes are in the two last commit). If the code is convincing, thats will be a great news for me. Thank´s in advanced

**Comment by soywiz** [comment]
Great :) Gracias.

Just make a Pull Request, and I will merge it.  If you can, it would be great to make a commit before the PR to enable disabled tests related to self (probably just move files), and also add a test that checks the absolute path behaviour working fine (failing before the fix, and working after the fix).

Thanks.

**Comment by InDIOS** [comment]
Thanks for the answer speed, gggggg, thats is amazing. Below i show you what is the bug with the use of the consolidate module:
![bug_atpl_consolidate](https://cloud.githubusercontent.com/assets/11496916/14238486/18cc9742-fa32-11e5-9f58-e456abb815db.png)
In the green rectangle you can look the configuration for atpl with consolidate and in the red rectangle the output error.
Here my solution:
![getsync_fixed](https://cloud.githubusercontent.com/assets/11496916/14238694/3f115328-fa34-11e5-83c1-136691a8aa4d.png)
In the next images you can see the test that i did, and the corresponding success output:
![maked_test](https://cloud.githubusercontent.com/assets/11496916/14238595/58dfad50-fa33-11e5-842e-4114cbb328ba.png)
![output_test](https://cloud.githubusercontent.com/assets/11496916/14238601/650a148a-fa33-11e5-8678-58f49874b0f6.png)
I will push all code today, when the work allows me to do, and "hechale un ojo" to see what do you think about it. Gracias a ti.
